### ISSUE TITLE
Initiate PC475 Baseline Pan-LN Combo. Re-score cell type and split by cell type.

### ISSUE THREAD

**Issue by bbimber** [bimberlabinternal/CellMembrane#104]

**Comment by bbimber** [comment]
The broad goal is to repeat Eisa's LN analysis no baseline PC475 data using the full dataset. We already have combos prepared with MesLN and pLN separately: https://prime-seq.ohsu.edu/query/Labs/Bimber/executeQuery.view?queryName=outputfiles&query.category~eq=Seurat%20Object&schemaName=sequenceanalysis&query.runid%2Fjobid%2FRowId~in=336690;336692

We need to run a job that:
- Starts with these objects
- Run the best-available cell type scoring
- Merges them
- Splits by cell type
- Runs the normal PCA/DimRedux steps

Then assign one of the resulting combos to Sebastian (B cells?) and you take the others. Inspect them to see if there are outlier or other questions cells to drop. After we're satisfied with the results, evaluate both the 'normal' dim redux based on top variable genes, and also repeat Eisa's semi-supervised dim redux that adds/removes specific genes (get that list from Eisa).

We will also need to separate CD4 and CD8s using our best available data, which might take some judgement. Because many cells will overlap with Eisa's earlier work, we can potentially transfer labels from his object to yours by simply matching cell barcodes. This might be a useful starting point.

**Comment by gboggy** [comment]
Here are the output files for splitting baseline lymph node data (merged pLN and MesLN) by cell type
https://prime-seq.ohsu.edu/query/Labs/Bimber/executeQuery.view?queryName=outputfiles&query.category~eq=Seurat%20Object&schemaName=sequenceanalysis&query.workbook%2FworkbookId~eq=800



The MesLN and pLN baseline seurat objects were
1. scored with Celltypist model (model_5_5_20_subset5000)
2. Merged
3. Split by cell type
4. processed
