### ISSUE TITLE
.GenerateSizeFactor doesn't sanitize normalizationField

### ISSUE THREAD

**Issue by GWMcElfresh** [bimberlabinternal/CellMembrane#113]
.GenerateSizeFactor fails if the data is a factor (due to zeroes in the resulting table), so it needs to be sanitized as either a string (default from the CellMembrane pipeline) or a number.

**Comment by bbimber** [comment]
do you plan to submit code on that? the change sounds simple? just an as.character() call or something?

**Comment by GWMcElfresh** [comment]
yeah, I intend to implement some logic around checking the inputs a bit better. 

I think I made a lot of implicit assumptions on `table()` calls that should return a single number vs an actual table. One day R might treat a table of characters as a table of factors or something, so I think being more explicit about it is a good idea.

**Comment by GWMcElfresh** [comment]
fixed with https://github.com/bimberlabinternal/CellMembrane/pull/114
