### ISSUE TITLE
 RunCellBender

### ISSUE THREAD

**Issue by areyoukidneyme** [bimberlabinternal/CellMembrane#115]
When I try running RunCellBender, I get this error:

**The cellbender python package has not been installed!**

Can you help me with this?

Thanks in advance!

**Comment by bbimber** [comment]
Thanks for your interest - the best guide on installing CellBender (which my lab does not make), is from their site: https://github.com/broadinstitute/CellBender. 

As you found, CellMembrane does have a function to run CellBender against data in a seurat object. My group has moved away form it (we using SoupX mainly), but it's certainly possible CellBender will be useful for some data. Depending on your use case, it's possible you'd do just as well running cellbender directly without needing our R package.

**Comment by areyoukidneyme** [comment]
Thanks! 

I've tried using SoupX and was just looking into CellBender for comparison. I was trying to use CellBender in Python but I am having issues with the codes which I also brought up with the CellBender makers.

Anyway, thanks for the recoms.

By the way, the idea of CellMembrane is awesome! Keep it up!
