### ISSUE TITLE
Not an issue, but an invitation for information exchange

### ISSUE THREAD

**Issue by derrik-gratz** [bimberlabinternal/CellMembrane#185]
I met Gregory at the NHP AIDS conference and discussed some analysis talking points and he pointed me to your package. We (Emory primate research center) are developing our own package in a similar pursuit (wrappers for single-cell analysis). Your package looks more advanced than ours, but I thought I'd share our efforts with you all in case there is something of use to you, or to possibly open discussions on certain methods. Thanks for developing this resource, I anticipate my colleagues and I will draw from it in our own workflow development. 

https://github.com/yerkes-gencore/gencoreSC
https://github.com/yerkes-gencore/gencoreBulk

**Comment by derrik-gratz** [comment]
Feel free to close this too, just wasn't sure how else to reach out 😄

**Comment by bbimber** [comment]
@derrik-gratz: thanks for reaching out. i'll try to look for you at the meeting. would be great to meet in person
