### ISSUE TITLE
PseudobulkingDEHeatmap with geneSpace with 1 gene only

### ISSUE THREAD

**Issue by daramirez** [bimberlabinternal/CellMembrane#248]
Is it possible to have the function "PseudobulkingDEHeatmap" to accept as geneSpace a vector of only 1 gene?
It currently does not support this, with the error message "Error: geneSpace must contain more than one gene. Please ensure geneSpace is a vector of gene names that you would like to plot in the heatmap."

**Comment by GWMcElfresh** [comment]
For posterity, we landed on "use a violin plot instead of a heatmap" for single gene genesets.
