### ISSUE TITLE
PseudobulkingBarPlot may want to check if there are any statistically significant DEGs

### ISSUE THREAD

**Issue by daramirez** [bimberlabinternal/CellMembrane#251]
PseudobulkingBarPlot may want to check if there are any statistically significant DEGs before attempting to make the bar plots. When the "DE_results" list has no genes in neither of its elements that would pass the logFC and FDR thresholds, the function currently errors with a cryptic message, which is because the changes on the data frame in line 785 yield a weird output when all genes are "noDEG" in the "regulation" column.

**Comment by GWMcElfresh** [comment]
Hi Daniel, thanks, this makes sense. Can you post the error message?

**Comment by daramirez** [comment]
Yes, here is a snapshot
![Screenshot 2024-05-28 at 2 06 04 PM](https://github.com/bimberlabinternal/CellMembrane/assets/22103816/a0486ae1-d661-4ebe-87d2-7d96312d029e)

**Comment by GWMcElfresh** [comment]
Hi @daramirez, does #253 fix this well enough?

**Comment by GWMcElfresh** [comment]
🎉 fixed well enough! 🎉
